### PR TITLE
implement #24

### PR DESCRIPTION
**Pull request by digitalpianism**
Here I'm using a small counter class as I think that's the method that involved the less refactoring to implement multiple captchas on the same page.

It also fixes the error when the script that retrieves the captcha library is called twice which results in an error in the console : "Uncaught Error: ReCAPTCHA placeholder element must be empty"

### CODE REVIEW

**Comment by digitalpianism** [comment]
Sorry for not writing tests 🙈

**Comment by colinmurphy** [comment]
Thanks digitalpianism ,

We will review this in the coming weeks.

Regards,
Colin

**Comment by digitalpianism** [comment]
@colinmurphy great thanks for that

**Comment by uvarovdev** [comment]
Works great. Thank you.

**Pull request closed without merging**
